// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Lab7Context))]
    [Migration("20230515071552_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rerum quibusdam excepturi doloribus dicta voluptates. Earum vero quasi sed architecto quod omnis. Debitis odit sunt natus cum eos et atque sunt a.",
                            Name = "Challenger"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Deserunt officiis qui voluptates. Deserunt aut qui magnam quis incidunt nihil. Quia neque magni sed animi sit aut natus culpa non.",
                            Name = "Wrangler"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modi perferendis et suscipit sed eius laboriosam rerum. Praesentium vel voluptates est suscipit tempore. Dolor unde voluptatem.",
                            Name = "El Camino"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dicta similique possimus voluptatem deserunt eveniet sit. Voluptatum praesentium labore. Aut et et. Totam velit enim sint omnis voluptatem. Sit iusto velit repellendus natus cupiditate vero unde. Ad qui ullam voluptatem quam voluptatibus et eveniet quibusdam sint.",
                            Name = "A8"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ullam dolor porro nostrum expedita est sunt ratione. Voluptatibus itaque et asperiores ipsam odio consequatur quas accusantium. Consequuntur labore repellendus autem repellendus.",
                            Name = "XC90"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Minima tempora officia ea officiis reprehenderit numquam minima optio. Aut sit provident quidem esse optio consequuntur quia est. Odio vitae accusamus soluta. Minus qui et. Animi eum quaerat sunt placeat dolorem ut enim quo.",
                            Name = "XC90"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Consequatur voluptates dolor. Quia vel dolor. Non quibusdam explicabo consequatur culpa quia. Molestias ex facilis. Dolores aliquam a veritatis et est corporis porro placeat molestias.",
                            Name = "Charger"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Inventore et voluptas. Consequatur voluptatem sapiente dolor quia atque quisquam et. Architecto temporibus quia vel ex dignissimos voluptatem in quaerat est.",
                            Name = "Cruze"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Deleniti cumque ut ab aperiam ducimus suscipit nobis eveniet. Consequatur qui voluptatem veritatis in debitis quisquam unde aut est. Fuga sint nemo at sit in. Ut eaque maxime sit dicta ut tenetur voluptatum. Consequatur nobis dignissimos et culpa officiis pariatur velit doloremque quaerat. Totam eius excepturi dolorem adipisci magnam corrupti facere aliquid.",
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sint illum laborum eaque nemo. Et molestiae hic voluptas illum perspiciatis ut velit vitae. Eveniet rem cumque. Eos ab ut ratione.",
                            Name = "Silverado"
                        });
                });

            modelBuilder.Entity("backend.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Ghana",
                            Name = "Lesch - Waters"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Virgin Islands, U.S.",
                            Name = "Stamm LLC"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Gabon",
                            Name = "Bernhard and Sons"
                        },
                        new
                        {
                            Id = 4,
                            Location = "French Guiana",
                            Name = "Strosin, Botsford and Barrows"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Fiji",
                            Name = "Nitzsche - Ernser"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Kenya",
                            Name = "Gibson Inc"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Peru",
                            Name = "Corwin Inc"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Christmas Island",
                            Name = "Murazik LLC"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Christmas Island",
                            Name = "Goodwin - Huel"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Chad",
                            Name = "Hirthe, Denesik and Adams"
                        });
                });

            modelBuilder.Entity("backend.Models.ManufacturerFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ManufacturerFood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodId = 1,
                            ManufacturerId = 9
                        },
                        new
                        {
                            Id = 2,
                            FoodId = 2,
                            ManufacturerId = 6
                        },
                        new
                        {
                            Id = 3,
                            FoodId = 3,
                            ManufacturerId = 4
                        },
                        new
                        {
                            Id = 4,
                            FoodId = 4,
                            ManufacturerId = 4
                        },
                        new
                        {
                            Id = 5,
                            FoodId = 5,
                            ManufacturerId = 3
                        },
                        new
                        {
                            Id = 6,
                            FoodId = 6,
                            ManufacturerId = 3
                        },
                        new
                        {
                            Id = 7,
                            FoodId = 7,
                            ManufacturerId = 6
                        },
                        new
                        {
                            Id = 8,
                            FoodId = 8,
                            ManufacturerId = 2
                        },
                        new
                        {
                            Id = 9,
                            FoodId = 9,
                            ManufacturerId = 1
                        },
                        new
                        {
                            Id = 10,
                            FoodId = 10,
                            ManufacturerId = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManufacturerId = 7,
                            Name = "Civic",
                            Speed = 182
                        },
                        new
                        {
                            Id = 2,
                            ManufacturerId = 9,
                            Name = "XC90",
                            Speed = 238
                        },
                        new
                        {
                            Id = 3,
                            ManufacturerId = 6,
                            Name = "Accord",
                            Speed = 302
                        },
                        new
                        {
                            Id = 4,
                            ManufacturerId = 5,
                            Name = "Model S",
                            Speed = 363
                        },
                        new
                        {
                            Id = 5,
                            ManufacturerId = 3,
                            Name = "Prius",
                            Speed = 284
                        },
                        new
                        {
                            Id = 6,
                            ManufacturerId = 5,
                            Name = "A4",
                            Speed = 131
                        },
                        new
                        {
                            Id = 7,
                            ManufacturerId = 5,
                            Name = "Wrangler",
                            Speed = 191
                        },
                        new
                        {
                            Id = 8,
                            ManufacturerId = 8,
                            Name = "Countach",
                            Speed = 105
                        },
                        new
                        {
                            Id = 9,
                            ManufacturerId = 10,
                            Name = "Taurus",
                            Speed = 244
                        },
                        new
                        {
                            Id = 10,
                            ManufacturerId = 10,
                            Name = "Land Cruiser",
                            Speed = 365
                        });
                });

            modelBuilder.Entity("backend.Models.ManufacturerFood", b =>
                {
                    b.HasOne("backend.Models.Food", "Food")
                        .WithMany("manufacturerFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Manufacturer", "Manufacturer")
                        .WithMany("ManufacturerFoods")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.HasOne("backend.Models.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("backend.Models.Food", b =>
                {
                    b.Navigation("manufacturerFoods");
                });

            modelBuilder.Entity("backend.Models.Manufacturer", b =>
                {
                    b.Navigation("ManufacturerFoods");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
